# IMPORT ENV DEV
spring.config.import=optional:file:.env.dev[.properties]

#app
app.cors.allowed-origins=http://localhost:5173
app.auth.redirect-url=http://localhost:5173/checksum
app.auth.redirect.url.password-reset=http://localhost:5173/auth/set-password

# JPA DEV
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true

# DATASOURCE DEV
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

# REDIS DEV
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.password=${REDIS_PWD_DEV}
spring.data.redis.ssl.enabled=false

spring.data.mongodb.database=audit_db
spring.data.mongodb.uri=mongodb://dev:dev1234@localhost:27017/audit_db?authSource=admin
spring.data.mongodb.auto-index-creation=true

# JWT DEV
jwt.secret.key=${JWT_SECRET}
jwt.secret.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

# APP DEV
app.uri=${APP_URI}
app.user.admin.email=${ADMIN_EMAIL}
app.user.admin.password=${ADMIN_PWD}
app.user.email=${USER_EMAIL}
app.user.password=${USER_PWD}

app.mapping.auth=${MAP_AUTH}
app.mapping.admin=${APP_ADMIN_MAPPING}
app.mapping.user=${APP_USER_MAPPING}

# OAUTH DEV
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.scope=email,public_profile

# STRIPE DEV
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.success-url=${STRIPE_SUCCESS_URL}
stripe.cancel-url=${STRIPE_CANCEL_URL}

# PAYMENT RECONCILIATION
app.payment.reconciliation.interval=300000

# MAIL DEV
spring.mail.host=${APP_MAIL_HOST}
spring.mail.port=${APP_MAIL_PORT}
spring.mail.username=${APP_MAIL_USER}
spring.mail.password=${APP_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.debug=true

app.backup.db.command.host=${BACKUP_HOST}
app.backup.db.command.port=${BACKUP_PORT}
app.backup.db.command.username=${DATASOURCE_USERNAME}
app.backup.db.command.password=${DATASOURCE_PASSWORD}
app.backup.db.command.database=${DB_NAME}
app.backup.db.command.directory=${user.home}/backups

app.scheduler.config.thread-name-prefix=scheduler-app-thread
app.scheduler.config.pool-size=10
app.scheduler.config.await-termination-seconds=30